name: Backend CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.10
          cache: 'pipenv'
      - run: pipenv install
      - run: pipenv run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10
          cache: 'pipenv'
      - run: pipenv install
      - run: pipenv run test
      

  build:
    needs: 
      - lint
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10
          cache: 'pipenv'
      - run: pipenv install
      - run: pipenv run test

      - name: Build Docker Image
        - name: Build Docker Image
        run: |
          docker build -t backend-ci:latest .
